services:
  - type: web
    name: newsnow
    runtime: docker
    region: oregon
    plan: starter
    healthCheckPath: /
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 4444
      - key: NODE_ENV
        value: production
      - key: INIT_TABLE
        value: true
      - key: ENABLE_CACHE
        value: true
      - key: G_CLIENT_ID
        sync: false
      - key: G_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: newsnow-data
      mountPath: /usr/app/.data
      sizeGB: 1
