/* eslint-disable */

declare module 'glob:./sources/{*.ts,**/index.ts}' {
  export const accuweather: typeof import('./sources/accuweather')
  export const apnews: typeof import('./sources/apnews')
  export const arstechnica: typeof import('./sources/arstechnica')
  export const bbc: typeof import('./sources/bbc')
  export const bloomberg: typeof import('./sources/bloomberg')
  export const cbc: typeof import('./sources/cbc')
  export const cnbc: typeof import('./sources/cnbc')
  export const cnn: typeof import('./sources/cnn')
  export const ctv: typeof import('./sources/ctv')
  export const engadget: typeof import('./sources/engadget')
  export const github: typeof import('./sources/github')
  export const globalnews: typeof import('./sources/globalnews')
  export const globeandmail: typeof import('./sources/globeandmail')
  export const guardian: typeof import('./sources/guardian')
  export const hackernews: typeof import('./sources/hackernews')
  export const marketwatch: typeof import('./sources/marketwatch')
  export const mcgillnews: typeof import('./sources/mcgillnews')
  export const nationalpost: typeof import('./sources/nationalpost')
  export const npr: typeof import('./sources/npr')
  export const nytimes: typeof import('./sources/nytimes')
  export const phys: typeof import('./sources/phys')
  export const reddit: typeof import('./sources/reddit')
  export const reuters: typeof import('./sources/reuters')
  export const sciencedaily: typeof import('./sources/sciencedaily')
  export const techcrunch: typeof import('./sources/techcrunch')
  export const theconversation: typeof import('./sources/theconversation')
  export const theverge: typeof import('./sources/theverge')
  export const torontostar: typeof import('./sources/torontostar')
  export const ubcnews: typeof import('./sources/ubcnews')
  export const universityaffairs: typeof import('./sources/universityaffairs')
  export const uoftoronto: typeof import('./sources/uoftoronto')
  export const weathernetwork: typeof import('./sources/weathernetwork')
  export const wired: typeof import('./sources/wired')
  export const yahoofinance: typeof import('./sources/yahoofinance')
}
